spring.application.name=Interswitch-Payment-Processing-System

server:
port: 8080
#  ssl:
#    enabled: true
#    key-store: classpath:keystore.p12
#    key-store-password: ${KEY_STORE_PASSWORD:yourpassword}
#    key-store-type: PKCS12

spring:
datasource:
url: jdbc:h2:mem:paymentdb;DB_CLOSE_DELAY=-1
username: sa
password: password
driver-class-name: org.h2.Driver
jpa:
hibernate:
ddl-auto: update
properties:
hibernate:
format_sql: true
h2:
console:
enabled: true
settings:
web-allow-others: false


security:
jwt:
secret: ${JWT_SECRET:KEY}
expiration: 86400000